on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  agent_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./agent
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        # Pin a particular version of pnpm action setup. This is the only
        # version allowed to run. If it needs to be updated, then it will need
        # a Flutter project GitHub admin to do it.
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          cache-dependency-path: ./agent
      - name: Install Dependencies
        run: pnpm install
      - name: Build Code
        run: pnpm run build
      - name: Run Tests
        run: pnpm test
