on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/code_search_mcp.yaml'
      - 'pkgs/code_search_mcp/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/code_search_mcp.yaml'
      - 'pkgs/code_search_mcp/**'

defaults:
  run:
    working-directory: pkgs/code_search_mcp/

jobs:
  analyze_and_test:
    name: Analyze and Test Python code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        id: install_deps
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
          pip install ruff

      - name: Lint with ruff
        if: steps.install_deps.outcome == 'success'
        run: ruff check .

      - name: Check formatting with ruff
        if: steps.install_deps.outcome == 'success'
        run: ruff format --check .

      - name: Run tests with pytest
        if: steps.install_deps.outcome == 'success'
        run: pytest
